version: '3.8'

services:
  redpanda-0:
    image: redpandadata/redpanda
    container_name: redpanda-0
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda-0:9092
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=redpanda-0:33145
      - --seeds=redpanda-0:33145,redpanda-1:33146,redpanda-2:33147
    ports:
      - "9092:9092"
      - "9644:9644"
    volumes:
      - redpanda-data-0:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9644/v1/status/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda-1:
    image: redpandadata/redpanda
    container_name: redpanda-1
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 1
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9093
      - --advertise-kafka-addr=PLAINTEXT://redpanda-1:9093
      - --rpc-addr=0.0.0.0:33146
      - --advertise-rpc-addr=redpanda-1:33146
      - --seeds=redpanda-0:33145,redpanda-1:33146,redpanda-2:33147
    ports:
      - "9093:9093"
      - "9645:9644"
    volumes:
      - redpanda-data-1:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9644/v1/status/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda-2:
    image: redpandadata/redpanda
    container_name: redpanda-2
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 2
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9094
      - --advertise-kafka-addr=PLAINTEXT://redpanda-2:9094
      - --rpc-addr=0.0.0.0:33147
      - --advertise-rpc-addr=redpanda-2:33147
      - --seeds=redpanda-0:33145,redpanda-1:33146,redpanda-2:33147
    ports:
      - "9094:9094"
      - "9646:9644"
    volumes:
      - redpanda-data-2:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9644/v1/status/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda-console:
    image: redpandadata/console
    container_name: redpanda-console
    ports:
      - "8081:8081"
    depends_on:
      - redpanda-0
    environment:
      REDPANDA_BROKER: redpanda-0:9092
      REDPANDA_CONSOLE_USERNAME: admin
      REDPANDA_CONSOLE_PASSWORD: admin

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-backend
    depends_on:
      - redpanda-0
    environment:
      REDPANDA_BROKER: redpanda-0:9092,redpanda-1:9093,redpanda-2:9094
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  web:
    image: nginx:alpine
    container_name: chat-web
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  redpanda-data-0:
  redpanda-data-1:
  redpanda-data-2:
